# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.
include: "rules/common.smk"
include: "rules/fastqc.smk"

report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
singularity: "docker://continuumio/miniconda3"

workdir: "scripts/"
rule all:
    input:
        expand("../../results/FastQC/{id}/{id}_fastqc.zip", id = config['samples'])
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.


include: "rules/common.smk"
include: "rules/other.smk"
