samples:
  unT5_REP3_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP3_2017_R2_test.fastq.gz'
  unT5_REP1_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP1_2017_R2_test.fastq.gz'
  T5_REP3_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP3_2017_R2_test.fastq.gz'
  unT5_REP2_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP2_2017_R2_test.fastq.gz'
  T5_REP3_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP3_2017_R1_test.fastq.gz'
  T5_REP1_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP1_2017_R2_test.fastq.gz'
  T5_REP2_2017_R2_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP2_2017_R2_test.fastq.gz'
  unT5_REP1_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP1_2017_R1_test.fastq.gz'
  unT5_REP2_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP2_2017_R1_test.fastq.gz'
  unT5_REP3_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/unT5_REP3_2017_R1_test.fastq.gz'
  T5_REP1_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP1_2017_R1_test.fastq.gz'
  T5_REP2_2017_R1_test : '/home/elsa/Luco_MAJIQ/snakemake_align_MAJIQ/resources/T5_REP2_2017_R1_test.fastq.gz'
date : '2021_01_13_16h43m24s'