$schema: "http://json-schema.org/draft-04/schema#"

description: snakemake configuration file

type: object

# possible entries of the config file and which type they should be
properties:
  NbRep:
    type: integer
  Samplespaired:
    type: object
  Samplesname:
    type: array
  Exp1:
    type: string
  Exp2:
    type: string

# entries that have to be in the config file for successful validation
required:
  - NbRep
  - Samplespaired
  - Samplesname
  - Exp1
  - Exp2

